# fly.toml app configuration file generated for grand-line on 2023-08-04T08:23:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grand-line"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
